name: Windows LiteManager Setup

on:
  workflow_dispatch:

jobs:
  lite-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LiteManager Server
        run: |
          msiexec /i "${{ github.workspace }}\litemanager_5\LiteManager Pro - Server.msi" /quiet /norestart

      - name: Start LiteManager Server
        run: |
          Start-Process "C:\Program Files (x86)\LiteManager Pro\LiteManagerServer.exe"

      - name: Display IP Address
        run: |
          ipconfig
